package com.hro.core.model.mapper;

import com.hro.core.model.MusicServerInfo;

public interface MusicServerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insert(MusicServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insertSelective(MusicServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    MusicServerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int updateByPrimaryKeySelective(MusicServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int updateByPrimaryKey(MusicServerInfo record);
}