package com.hro.core.model.mapper;

import com.hro.core.model.PicInfo;

public interface PicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insert(PicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insertSelective(PicInfo record);
}