package com.hro.core.model.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hro.core.common.util.QueryParams;
import com.hro.core.model.HotelBaseInfo;

public interface HotelBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_base_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_base_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insert(HotelBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_base_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insertSelective(HotelBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_base_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    HotelBaseInfo selectByPrimaryKey(String id);
    
    /**
     * 查询酒店基本信息
     * @param params 查询参数
     * @return
     */
    List<HotelBaseInfo> findHotelInfoPage(QueryParams params);
    
    /**
     * 根据查询条件统计酒店基本信息
     * @param params 查询参数
     * @return
     */
    Integer findHotelInfoTotal(QueryParams params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_base_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int updateByPrimaryKeySelective(HotelBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_base_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int updateByPrimaryKey(HotelBaseInfo record);
    
    /**
     * 根据ID删除数据
     * @param ids
     * @return
     */
    int deleteByIds(@Param("ids") List<String> ids);
}