package com.hro.core.model;

import java.util.List;

public class MusicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.MUSIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String musicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.SINGER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String singerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.MUSIC_SERVER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String musicServerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.PHYSICAL_MUSIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String physicalMusicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.VIRTUAL_MUSIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String virtualMusicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_info.MUSIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private Integer musicType;
    
    /**
     * 跟图片是1对多的关系
     */
    private List<PicInfo> picInfos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.ID
     *
     * @return the value of music_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.ID
     *
     * @param id the value for music_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.MUSIC_NAME
     *
     * @return the value of music_info.MUSIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getMusicName() {
        return musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.MUSIC_NAME
     *
     * @param musicName the value for music_info.MUSIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setMusicName(String musicName) {
        this.musicName = musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.UPDATE_TIME
     *
     * @return the value of music_info.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.UPDATE_TIME
     *
     * @param updateTime the value for music_info.UPDATE_TIME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.SINGER_ID
     *
     * @return the value of music_info.SINGER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getSingerId() {
        return singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.SINGER_ID
     *
     * @param singerId the value for music_info.SINGER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setSingerId(String singerId) {
        this.singerId = singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.MUSIC_SERVER_ID
     *
     * @return the value of music_info.MUSIC_SERVER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getMusicServerId() {
        return musicServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.MUSIC_SERVER_ID
     *
     * @param musicServerId the value for music_info.MUSIC_SERVER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setMusicServerId(String musicServerId) {
        this.musicServerId = musicServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.PHYSICAL_MUSIC_PATH
     *
     * @return the value of music_info.PHYSICAL_MUSIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getPhysicalMusicPath() {
        return physicalMusicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.PHYSICAL_MUSIC_PATH
     *
     * @param physicalMusicPath the value for music_info.PHYSICAL_MUSIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPhysicalMusicPath(String physicalMusicPath) {
        this.physicalMusicPath = physicalMusicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.VIRTUAL_MUSIC_PATH
     *
     * @return the value of music_info.VIRTUAL_MUSIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getVirtualMusicPath() {
        return virtualMusicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.VIRTUAL_MUSIC_PATH
     *
     * @param virtualMusicPath the value for music_info.VIRTUAL_MUSIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setVirtualMusicPath(String virtualMusicPath) {
        this.virtualMusicPath = virtualMusicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_info.MUSIC_TYPE
     *
     * @return the value of music_info.MUSIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public Integer getMusicType() {
        return musicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_info.MUSIC_TYPE
     *
     * @param musicType the value for music_info.MUSIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setMusicType(Integer musicType) {
        this.musicType = musicType;
    }

	public List<PicInfo> getPicInfos() {
		return picInfos;
	}

	public void setPicInfos(List<PicInfo> picInfos) {
		this.picInfos = picInfos;
	}
    
}