package com.hro.core.model;

public class PicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.PIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.PHYSICAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String physicalPicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.VIRTUAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String virtualPicPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.PIC_SERVER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String picServerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.PIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private Integer picType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic_info.FK_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    private String fkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.ID
     *
     * @return the value of pic_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.ID
     *
     * @param id the value for pic_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PIC_NAME
     *
     * @return the value of pic_info.PIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PIC_NAME
     *
     * @param picName the value for pic_info.PIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PHYSICAL_PIC_PATH
     *
     * @return the value of pic_info.PHYSICAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getPhysicalPicPath() {
        return physicalPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PHYSICAL_PIC_PATH
     *
     * @param physicalPicPath the value for pic_info.PHYSICAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPhysicalPicPath(String physicalPicPath) {
        this.physicalPicPath = physicalPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.VIRTUAL_PIC_PATH
     *
     * @return the value of pic_info.VIRTUAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getVirtualPicPath() {
        return virtualPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.VIRTUAL_PIC_PATH
     *
     * @param virtualPicPath the value for pic_info.VIRTUAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setVirtualPicPath(String virtualPicPath) {
        this.virtualPicPath = virtualPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PIC_SERVER_ID
     *
     * @return the value of pic_info.PIC_SERVER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getPicServerId() {
        return picServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PIC_SERVER_ID
     *
     * @param picServerId the value for pic_info.PIC_SERVER_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPicServerId(String picServerId) {
        this.picServerId = picServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PIC_TYPE
     *
     * @return the value of pic_info.PIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PIC_TYPE
     *
     * @param picType the value for pic_info.PIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.FK_ID
     *
     * @return the value of pic_info.FK_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getFkId() {
        return fkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.FK_ID
     *
     * @param fkId the value for pic_info.FK_ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setFkId(String fkId) {
        this.fkId = fkId;
    }
}