package com.hro.core.mongo.vo;

import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.annotations.Reference;

@Entity
public class PicInfo {
	@Id
    private String id;				//主键
    private String picName;			//图片名称
    private String physicalPicPath;	//物理路径
    private String virtualPicPath;	//虚拟目录
    private Integer picType;		//图片类型
    private String groupId;			//组合ID
    @Reference
    private PicServerInfo picServerInfo;	//存储服务器

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.ID
     *
     * @return the value of pic_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.ID
     *
     * @param id the value for pic_info.ID
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PIC_NAME
     *
     * @return the value of pic_info.PIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PIC_NAME
     *
     * @param picName the value for pic_info.PIC_NAME
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PHYSICAL_PIC_PATH
     *
     * @return the value of pic_info.PHYSICAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getPhysicalPicPath() {
        return physicalPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PHYSICAL_PIC_PATH
     *
     * @param physicalPicPath the value for pic_info.PHYSICAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPhysicalPicPath(String physicalPicPath) {
        this.physicalPicPath = physicalPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.VIRTUAL_PIC_PATH
     *
     * @return the value of pic_info.VIRTUAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public String getVirtualPicPath() {
        return virtualPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.VIRTUAL_PIC_PATH
     *
     * @param virtualPicPath the value for pic_info.VIRTUAL_PIC_PATH
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setVirtualPicPath(String virtualPicPath) {
        this.virtualPicPath = virtualPicPath;
    }

    public PicServerInfo getPicServerInfo() {
		return picServerInfo;
	}

	public void setPicServerInfo(PicServerInfo picServerInfo) {
		this.picServerInfo = picServerInfo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic_info.PIC_TYPE
     *
     * @return the value of pic_info.PIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic_info.PIC_TYPE
     *
     * @param picType the value for pic_info.PIC_TYPE
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}
}