package com.hro.core.model.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hro.core.common.util.QueryParams;
import com.hro.core.model.PicServerInfo;

public interface PicServerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insert(PicServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int insertSelective(PicServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    PicServerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int updateByPrimaryKeySelective(PicServerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic_server_info
     *
     * @mbggenerated Thu Mar 24 17:15:49 CST 2016
     */
    int updateByPrimaryKey(PicServerInfo record);
    
    /**
     * 分页查询
     * @param params 查询参数
     * @return
     */
    List<PicServerInfo> findInfoPage(QueryParams params);
    
    /**
     * 根据查询条件统计记录总数
     * @param params 查询参数
     * @return
     */
    Integer findPageInfoTotal(QueryParams params);
    
    /**
     * 根据ID删除数据
     * @param ids
     * @return
     */
    int deleteByIds(@Param("ids") List<String> ids);
}